//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Unity.VisualScripting.Generated.PropertyProviders
{
	
	
	[global::Unity.VisualScripting.SerializedPropertyProviderAttribute(typeof(global::Com.Sabattie.Theo.ScriptTemplateSettings.RegexHelper))]
	public class PropertyProvider_Com_Sabattie_Theo_ScriptTemplateSettings_RegexHelper : Unity.VisualScripting.SerializedPropertyProvider<Com.Sabattie.Theo.ScriptTemplateSettings.RegexHelper>
	{
	}
}
